---
- name: Setup web server
  hosts: dev
  become: true
  become_user: deploy

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - Stouts.apt
    - deploy_user
    - sendmail
    - azavea.golang
    - node
    - node-modules
    - ANXS.oracle-jdk
    - ANXS.scala
    - ANXS.postgresql
    - Stouts.nginx
    - Stouts.redis
    - Stouts.grafana
