---
apt_enabled: yes                  # Enable the role
apt_cache_valid_time: 3600        # Time (in seconds) the apt cache stays valid
apt_upgrade: safe                 # Perfoms aptupgrade. Values are (safe, full, dist)
apt_install_recommends: no        # Install the "recommended" packages
apt_install_suggests: no          # Install the "suggested" packages
apt_sources_reset: no             # Mute original APT sources (it is intended to use a mirror directly)

apt_default_packages_install: yes   # Install some packages (see list bellow)
apt_default_packages:               # List of packages which will be installed
  - command-not-found
  - vim
  - curl
  - wget
  - unzip
  - git
  - mercurial
  - fping
  - htop
  - iftop
  - iotop
  - nmap
  - pciutils
  - screen
  - sysstat
  - build-essential
  - python-apt
  - python-pip
  - python-dev
  - python-virtualenv
  - libfontconfig         # phantomjs
  - redis-tools
